
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import type { ReactNode } from "react";
import { AuthProvider } from "@/context/AuthContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Anurag Kurmi",
  description: "Generated by create next app by Anurag Kurmi",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          {children}
        </AuthProvider>
        <Toaster
          position="top-right"
          toastOptions={{
            success: {
              duration: 3000,
              style: { background: "#22c55e", color: "#fff" }, // green toast
            },
            error: {
              duration: 4000,
              style: { background: "#ef4444", color: "#fff" }, // red toast
            },
            style: {
              borderRadius: "10px",
              fontWeight: 500,
            },
          }}
        />
      </body>
    </html>
  );
}
